# Generated by Django 5.0.6 on 2024-06-12 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Users", "0001_initial"),
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Wishlist",
            fields=[
                (
                    "customer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="Users.customerprofile",
                    ),
                ),
                (
                    "product",
                    models.ManyToManyField(blank=True, to="catalog.productdetail"),
                ),
            ],
            options={
                "db_table": "wishlist",
            },
        ),
    ]
