# Generated by Django 4.2.11 on 2024-05-20 12:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("address", "0001_initial"),
        ("Users", "0001_initial"),
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShoppingCart",
            fields=[
                (
                    "customer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="Users.customerprofile",
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
            ],
            options={
                "db_table": "shoppingcart",
            },
        ),
        migrations.CreateModel(
            name="ShoppingCartProducts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=1)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.productdetail",
                    ),
                ),
                (
                    "shopping_cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shopping_cart",
                        to="shoppingcart_and_order.shoppingcart",
                    ),
                ),
            ],
            options={
                "db_table": "shoppingcartproducts",
            },
        ),
        migrations.AddField(
            model_name="shoppingcart",
            name="products",
            field=models.ManyToManyField(
                blank=True,
                through="shoppingcart_and_order.ShoppingCartProducts",
                to="catalog.productdetail",
            ),
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("date_deliverd", models.DateTimeField(blank=True, null=True)),
                (
                    "order_status",
                    models.CharField(
                        choices=[
                            ("Preprocessing", "Preprocessing"),
                            ("Awaiting Pickup", "Awaiting Pickup"),
                            ("Picked up", "Picked up"),
                            ("Deliverd", "Deliverd"),
                            ("Cancelled", "Cancelled"),
                        ],
                        default="Preprocessing",
                        max_length=30,
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "order_address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="address.address",
                    ),
                ),
                (
                    "shopping_cart",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shoppingcart_and_order.shoppingcart",
                    ),
                ),
            ],
            options={
                "db_table": "order",
            },
        ),
    ]
