# Generated by Django 4.2 on 2024-04-04 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("shoppingcart_and_order", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="shoppingcart", name="id",),
        migrations.AlterField(
            model_name="shoppingcart",
            name="customer",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
