# Generated by Django 4.2 on 2024-04-05 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "__first__"),
        (
            "shoppingcart_and_order",
            "0002_remove_shoppingcart_id_alter_shoppingcart_customer",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="shoppingcart",
            name="products",
            field=models.ManyToManyField(blank=True, to="catalog.product"),
        ),
    ]
