# Generated by Django 4.2 on 2024-04-05 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shoppingcart_and_order", "0003_shoppingcart_products"),
    ]

    operations = [
        migrations.RenameField(
            model_name="shoppingcart", old_name="products", new_name="product",
        ),
    ]
