# Generated by Django 4.2 on 2024-04-08 03:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("catalog", "__first__"),
        ("shoppingcart_and_order", "0004_rename_products_shoppingcart_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("date_deliverd", models.DateTimeField(blank=True)),
                (
                    "order_status",
                    models.CharField(
                        choices=[
                            ("Preprocessing", "Preprocessing"),
                            ("Awaiting Pickup", "Awaiting Pickup"),
                            ("Picked up", "Picked up"),
                            ("Deliverd", "Deliverd"),
                            ("Cancelled", "Cancelled"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("product", models.ManyToManyField(to="catalog.product")),
            ],
            options={"db_table": "order",},
        ),
    ]
