# Generated by Django 4.2 on 2024-04-08 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shoppingcart_and_order", "0005_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="date_deliverd",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
