# Generated by Django 4.2 on 2024-03-27 18:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=30, null=True)),
                ("last_name", models.CharField(blank=True, max_length=30, null=True)),
                ("email", models.EmailField(blank=True, max_length=200, null=True)),
                ("password", models.CharField(blank=True, max_length=256, null=True)),
                ("date_joined", models.DateField(auto_now_add=True)),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="Users.user",
                    ),
                ),
                (
                    "Role",
                    models.CharField(
                        choices=[
                            ("admin", "admin"),
                            ("content_manager", "content_manager"),
                        ],
                        max_length=30,
                    ),
                ),
            ],
            options={"db_table": "Admin",},
            bases=("Users.user",),
        ),
    ]
