# Generated by Django 4.2 on 2024-03-27 19:00

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=30, null=True)),
                ("last_name", models.CharField(blank=True, max_length=30, null=True)),
                ("email", models.EmailField(blank=True, max_length=200, null=True)),
                ("password", models.CharField(max_length=256)),
                ("date_joined", models.DateField(default=django.utils.timezone.now)),
            ],
            options={"db_table": "Customer",},
        ),
        migrations.CreateModel(
            name="CustomerSupporter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=30, null=True)),
                ("last_name", models.CharField(blank=True, max_length=30, null=True)),
                ("email", models.EmailField(blank=True, max_length=200, null=True)),
                ("password", models.CharField(max_length=256)),
                ("date_joined", models.DateField(default=django.utils.timezone.now)),
            ],
            options={"db_table": "CustomerSupporter",},
        ),
        migrations.CreateModel(
            name="Driver",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=30, null=True)),
                ("last_name", models.CharField(blank=True, max_length=30, null=True)),
                ("email", models.EmailField(blank=True, max_length=200, null=True)),
                ("password", models.CharField(max_length=256)),
                ("date_joined", models.DateField(default=django.utils.timezone.now)),
            ],
            options={"db_table": "Driver",},
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=30, null=True)),
                ("last_name", models.CharField(blank=True, max_length=30, null=True)),
                ("email", models.EmailField(blank=True, max_length=200, null=True)),
                ("password", models.CharField(max_length=256)),
                ("date_joined", models.DateField(default=django.utils.timezone.now)),
                ("website", models.URLField()),
            ],
            options={"db_table": "Supplier",},
        ),
        migrations.AlterField(
            model_name="user",
            name="date_joined",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="user", name="password", field=models.CharField(max_length=256),
        ),
        migrations.AlterModelTable(name="user", table="User",),
        migrations.DeleteModel(name="Admin",),
    ]
