# Generated by Django 5.0.6 on 2024-07-15 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerprofile",
            name="fcm_token",
            field=models.CharField(default="empty", max_length=100),
        ),
    ]
