# Generated by Django 5.0.6 on 2024-07-09 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="driverprofile",
            name="user",
        ),
        migrations.DeleteModel(
            name="Driver",
        ),
        migrations.DeleteModel(
            name="DriverProfile",
        ),
    ]
