# Generated by Django 4.2 on 2024-04-06 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0002_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="address_name",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="address",
            name="city",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="address",
            name="district",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
