# Generated by Django 5.0.6 on 2024-07-17 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0002_customerprofile_fcm_token"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customerprofile",
            name="fcm_token",
        ),
    ]
