# Generated by Django 4.2 on 2024-03-27 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0002_customer_customersupporter_driver_supplier_and_more"),
    ]

    operations = [
        migrations.DeleteModel(name="User",),
    ]
