# Generated by Django 4.2 on 2024-04-07 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0003_alter_address_address_name_alter_address_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="address_name",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
