# Generated by Django 5.0.6 on 2024-07-17 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0003_remove_customerprofile_fcm_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerprofile",
            name="image_url",
            field=models.ImageField(
                default="customer_profile/default.png", upload_to="customer_profile"
            ),
        ),
    ]
