# Generated by Django 4.2 on 2024-03-27 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0004_admin_user"),
    ]

    operations = [
        migrations.AlterModelTable(name="admin", table="admin",),
    ]
