# Generated by Django 4.2 on 2024-04-07 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0004_alter_address_address_name"),
    ]

    operations = [
        migrations.DeleteModel(name="Address",),
    ]
