# Generated by Django 4.2 on 2024-03-27 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0005_alter_admin_table"),
    ]

    operations = [
        migrations.DeleteModel(name="Customer",),
    ]
