# Generated by Django 4.2 on 2024-04-07 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0006_address"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="address", unique_together={("customer", "address_name")},
        ),
    ]
