# Generated by Django 4.2 on 2024-03-27 19:05

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0006_delete_customer"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=30, null=True)),
                ("last_name", models.CharField(blank=True, max_length=30, null=True)),
                ("email", models.EmailField(blank=True, max_length=200, null=True)),
                ("password", models.CharField(max_length=256)),
                ("date_joined", models.DateField(default=django.utils.timezone.now)),
            ],
            options={"db_table": "Customer",},
        ),
        migrations.AlterModelTable(name="admin", table="Admin",),
    ]
