# Generated by Django 5.0.6 on 2024-07-13 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Users", "0001_initial"),
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShoppingCart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "customer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Users.customerprofile",
                    ),
                ),
            ],
            options={
                "db_table": "shoppingcart",
            },
        ),
        migrations.CreateModel(
            name="ShoppingCartProducts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=1)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.productdetail",
                    ),
                ),
                (
                    "shopping_cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shopping_cart",
                        to="wishlist_cart.shoppingcart",
                    ),
                ),
            ],
            options={
                "db_table": "shoppingcartproducts",
            },
        ),
        migrations.AddField(
            model_name="shoppingcart",
            name="products",
            field=models.ManyToManyField(
                blank=True,
                through="wishlist_cart.ShoppingCartProducts",
                to="catalog.productdetail",
            ),
        ),
        migrations.CreateModel(
            name="Wishlist",
            fields=[
                (
                    "customer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="Users.customerprofile",
                    ),
                ),
                (
                    "product",
                    models.ManyToManyField(blank=True, to="catalog.productdetail"),
                ),
            ],
            options={
                "db_table": "wishlist",
            },
        ),
    ]
