# Generated by Django 5.0.6 on 2024-07-20 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_alter_categoriesbrand_brand"),
        ("wishlist_cart", "0002_alter_shoppingcart_total_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shoppingcartproducts",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart_product_det",
                to="catalog.productdetail",
            ),
        ),
    ]
