# Generated by Django 5.0.6 on 2024-07-21 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wishlist_cart", "0003_alter_shoppingcartproducts_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shoppingcart",
            name="total_price",
            field=models.IntegerField(default=0),
        ),
    ]
