# Generated by Django 5.0.6 on 2024-08-23 17:26

import django.contrib.auth.models
import django.db.models.deletion
import django.db.models.manager
import driver.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Users", "0001_initial"),
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Driver",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("Users.user",),
            managers=[
                ("driver", django.db.models.manager.Manager()),
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="DriverProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_approved", models.BooleanField(default=False)),
                (
                    "latitude",
                    models.FloatField(
                        default=0.0, validators=[driver.utils.validate_lat]
                    ),
                ),
                (
                    "longitude",
                    models.FloatField(
                        default=0.0, validators=[driver.utils.validate_long]
                    ),
                ),
                ("phone_number", models.CharField(max_length=15, unique=True)),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[("BIKE", "Bike"), ("CAR", "Car"), ("TRUCK", "Truck")],
                        max_length=9,
                    ),
                ),
                ("vehicle_plate", models.CharField(max_length=10, unique=True)),
                (
                    "vehicle_image",
                    models.ImageField(default="drivers/default", upload_to="driver"),
                ),
                ("is_online", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="vehicletypecategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[("BIKE", "Bike"), ("CAR", "Car"), ("TRUCK", "Truck")],
                        max_length=9,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.category",
                    ),
                ),
            ],
            options={
                "db_table": "vehicletypecategory",
            },
        ),
    ]
