# Generated by Django 5.0.6 on 2024-07-16 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("driver", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="driverprofile",
            name="vehicle_image",
            field=models.ImageField(default="drivers/default", upload_to="driver"),
        ),
        migrations.AddField(
            model_name="driverprofile",
            name="vehicle_plate",
            field=models.CharField(default="asdf", max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="driverprofile",
            name="vehicle_type",
            field=models.CharField(
                choices=[("BIKE", "Bike"), ("CAR", "Car"), ("TRUCK", "Truck")],
                default="Bike",
                max_length=9,
            ),
            preserve_default=False,
        ),
    ]
