# Generated by Django 5.0.6 on 2024-07-16 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("driver", "0002_driverprofile_vehicle_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="driverprofile",
            name="is_online",
            field=models.BooleanField(default=True),
        ),
    ]
