# Generated by Django 5.0.6 on 2024-07-22 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_alter_categoriesbrand_brand"),
        ("driver", "0003_driverprofile_is_online"),
    ]

    operations = [
        migrations.CreateModel(
            name="vehicletypecategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[("BIKE", "Bike"), ("CAR", "Car"), ("TRUCK", "Truck")],
                        max_length=9,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.category",
                    ),
                ),
            ],
            options={
                "db_table": "vehicletypecategory",
            },
        ),
    ]
