# Generated by Django 5.0.6 on 2024-07-09 14:52

import address.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0002_remove_driverprofile_user_delete_driver_and_more"),
        ("address", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="latitude",
            field=models.FloatField(
                default=0.0, validators=[address.utils.validate_lat]
            ),
        ),
        migrations.AddField(
            model_name="address",
            name="longitude",
            field=models.FloatField(
                default=0.0, validators=[address.utils.validate_long]
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Users.customerprofile"
            ),
        ),
    ]
