# Generated by Django 5.0.6 on 2024-07-10 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("address", "0002_address_latitude_address_longitude_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="phone_number",
            field=models.CharField(max_length=10),
        ),
    ]
