# Generated by Django 5.0.6 on 2024-06-21 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Users", "0001_initial"),
        ("catalog", "0001_initial"),
        ("supplier", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Promotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                ("discount_percentege", models.IntegerField()),
                ("time_start", models.DateField()),
                ("time_end", models.DateField()),
                ("is_active", models.BooleanField(default=False)),
                ("is_scheduled", models.BooleanField(default=True)),
                ("image_url", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "db_table": "promotion",
            },
        ),
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("coupon_code", models.CharField(max_length=10)),
                (
                    "discount_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=7,
                        null=True,
                        unique=True,
                    ),
                ),
                ("user_max_use", models.IntegerField(blank=True, null=True)),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="supplier.supplierprofile",
                    ),
                ),
            ],
            options={
                "db_table": "coupon",
            },
        ),
        migrations.CreateModel(
            name="ProductOnPromotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products_on_promotion",
                        to="catalog.product",
                    ),
                ),
                (
                    "promotion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="promotion.promotion",
                    ),
                ),
            ],
            options={
                "db_table": "product_promotion",
            },
        ),
        migrations.CreateModel(
            name="UsedCoupons",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("used_coupons", models.IntegerField()),
                (
                    "coupon_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="used_coupons",
                        to="promotion.coupon",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Users.customerprofile",
                    ),
                ),
            ],
            options={
                "db_table": "usedcoupons",
            },
        ),
    ]
