# Generated by Django 5.0.6 on 2024-08-23 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Users", "0001_initial"),
        ("inventory", "0001_initial"),
        ("supplier", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Promotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                ("discount_percentege", models.IntegerField()),
                ("time_start", models.DateField()),
                ("time_end", models.DateField()),
                ("is_active", models.BooleanField(default=False)),
                ("is_scheduled", models.BooleanField(default=True)),
                (
                    "image_url",
                    models.ImageField(
                        default="promotions/default.png", upload_to="promotions"
                    ),
                ),
            ],
            options={
                "db_table": "promotion",
            },
        ),
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("coupon_code", models.CharField(max_length=10)),
                ("discount_value", models.IntegerField()),
                ("user_max_use", models.IntegerField(blank=True, null=True)),
                ("products_to_earn", models.IntegerField()),
                ("time_start", models.DateField(default="2025-05-04")),
                ("time_end", models.DateField(default="2025-05-05")),
                ("is_active", models.BooleanField(default=False)),
                (
                    "supplier",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="supplier.supplierprofile",
                    ),
                ),
            ],
            options={
                "db_table": "coupon",
            },
        ),
        migrations.CreateModel(
            name="ProductOnPromotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products_on_promotion",
                        to="inventory.product",
                    ),
                ),
                (
                    "promotion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="promotion.promotion",
                    ),
                ),
            ],
            options={
                "db_table": "product_promotion",
            },
        ),
        migrations.CreateModel(
            name="UsedCoupons",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("times_used", models.IntegerField(default=0)),
                (
                    "coupon_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="used_coupons",
                        to="promotion.coupon",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_coupon",
                        to="Users.customerprofile",
                    ),
                ),
            ],
            options={
                "db_table": "usedcoupons",
            },
        ),
    ]
