# Generated by Django 5.0.6 on 2024-07-17 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("promotion", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="products_to_earn",
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
