# Generated by Django 5.0.6 on 2024-06-22 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("promotion", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="promotion",
            name="image_url",
            field=models.ImageField(
                default="promotions/default.png", upload_to="promotions"
            ),
        ),
    ]
