# Generated by Django 4.2.11 on 2024-05-21 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
        ("promotion", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productonpromotion",
            name="product",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products_on_promotion",
                to="catalog.product",
            ),
        ),
        migrations.AlterField(
            model_name="productonpromotion",
            name="promotion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="promotion.promotion"
            ),
        ),
    ]
