# Generated by Django 5.0.6 on 2024-07-18 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("promotion", "0002_coupon_products_to_earn"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="time_end",
            field=models.DateField(default="2025-05-05"),
        ),
        migrations.AddField(
            model_name="coupon",
            name="time_start",
            field=models.DateField(default="2025-05-04"),
        ),
    ]
