# Generated by Django 5.0.6 on 2024-07-20 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("promotion", "0004_coupon_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupon",
            name="discount_value",
            field=models.IntegerField(),
        ),
    ]
