# Generated by Django 5.0.6 on 2024-07-21 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("promotion", "0005_alter_coupon_discount_value"),
        ("supplier", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupon",
            name="supplier",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="supplier.supplierprofile",
            ),
        ),
    ]
