# Generated by Django 5.0.6 on 2024-07-21 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0004_customerprofile_image_url"),
        ("promotion", "0006_alter_coupon_supplier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usedcoupons",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer_coupon",
                to="Users.customerprofile",
            ),
        ),
    ]
