# Generated by Django 5.0.6 on 2024-06-12 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="product",
            name="product_embedding_hnsw_index",
        ),
        migrations.RemoveField(
            model_name="product",
            name="embedding",
        ),
    ]
