# Generated by Django 4.2.11 on 2024-05-25 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="main_image",
            field=models.CharField(max_length=255),
        ),
    ]
