# Generated by Django 4.2.11 on 2024-05-23 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="description",
        ),
        migrations.AlterField(
            model_name="productcolor",
            name="color",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="productsize",
            name="product_size",
            field=models.CharField(max_length=50),
        ),
    ]
