# Generated by Django 4.2 on 2024-04-01 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        
        
        migrations.AlterField(
            model_name="product", name="price", field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="product",
            name="times_bought",
            field=models.IntegerField(default=0),
        ),
    ]
