# Generated by Django 5.0.6 on 2024-07-13 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_category_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="main_image",
            field=models.CharField(max_length=255),
        ),
    ]
