# Generated by Django 5.0.6 on 2024-06-12 16:37

import pgvector.django
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0001_initial"),
        ("catalog", "0002_remove_product_product_embedding_hnsw_index_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="embedding",
            field=pgvector.django.VectorField(blank=True, dimensions=384, null=True),
        ),
        migrations.AddIndex(
            model_name="product",
            index=pgvector.django.HnswIndex(
                ef_construction=64,
                fields=["embedding"],
                m=16,
                name="product_embedding_hnsw_index",
                opclasses=["vector_cosine_ops"],
            ),
        ),
    ]
