# Generated by Django 4.2.11 on 2024-05-12 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_productdetail_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="main_price",
            field=models.DecimalField(decimal_places=2, default=0.01, max_digits=10),
        ),
    ]
