# Generated by Django 4.2 on 2024-03-31 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_category_name_subcategory_name_alter_product_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="product", name="sub_category",),
        migrations.AddField(
            model_name="product",
            name="sub_category",
            field=models.ManyToManyField(to="catalog.subcategory"),
        ),
    ]
