# Generated by Django 5.0.6 on 2024-07-10 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_brand_product_brand"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="brand",
            name="category",
        ),
        migrations.CreateModel(
            name="CategoriesBrand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="catalog.brand"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.category",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="brand",
            name="cateogry",
            field=models.ManyToManyField(
                blank=True, through="catalog.CategoriesBrand", to="catalog.category"
            ),
        ),
    ]
