# Generated by Django 4.2.11 on 2024-05-12 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_product_main_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="average_rating",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="reviews_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_images",
                to="catalog.product",
            ),
        ),
    ]
