# Generated by Django 5.0.6 on 2024-07-10 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_remove_brand_category_categoriesbrand_brand_cateogry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="name",
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
