# Generated by Django 4.2 on 2024-04-01 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_remove_product_sub_category_product_sub_category"),
    ]

    operations = [
        migrations.RemoveField(model_name="product", name="slug",),
        migrations.RemoveField(model_name="subcategory", name="slug",),
    ]
