# Generated by Django 5.0.6 on 2024-07-13 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_product_main_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoriesbrand",
            name="brand",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="brand",
                to="catalog.brand",
            ),
        ),
    ]
