# Generated by Django 5.0.6 on 2024-07-22 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_alter_categoriesbrand_brand"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="average_rating",
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
