# Generated by Django 4.2.11 on 2024-05-12 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_product_average_rating_product_reviews_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="average_rating",
            field=models.FloatField(default=0),
        ),
    ]
