# Generated by Django 4.2 on 2024-04-01 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_remove_product_slug_remove_subcategory_slug"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category", old_name="name", new_name="category_name",
        ),
        migrations.RenameField(
            model_name="product", old_name="name", new_name="product_name",
        ),
        migrations.RenameField(
            model_name="subcategory", old_name="name", new_name="sub_category_name",
        ),
    ]
