# Generated by Django 4.2 on 2024-04-01 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_rename_name_category_category_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="subcategory",
            name="sub_category_name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
