# Generated by Django 4.2 on 2024-04-01 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_alter_category_category_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="category_name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
