# Generated by Django 4.2.11 on 2024-05-13 21:28

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_alter_product_managers_alter_productdetail_managers"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="category",
            managers=[
                ("active_categories", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="is_main",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="main_image",
            field=models.ImageField(default="images/default.png", upload_to="images/"),
        ),
        migrations.AddField(
            model_name="productdetail",
            name="image_url",
            field=models.ImageField(default="images/default.png", upload_to="images/"),
        ),
        migrations.DeleteModel(
            name="ProductImage",
        ),
    ]
