# Generated by Django 4.2 on 2024-04-01 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_alter_category_category_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category", old_name="category_name", new_name="name",
        ),
    ]
