# Generated by Django 4.2.11 on 2024-05-14 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_alter_category_managers_product_is_main_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="is_main",
        ),
        migrations.RemoveField(
            model_name="productdetail",
            name="image_url",
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_main", models.BooleanField(default=False)),
                (
                    "image_url",
                    models.ImageField(
                        default="images/default.png", upload_to="images/"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="catalog.product",
                    ),
                ),
            ],
        ),
    ]
