# Generated by Django 5.0.6 on 2024-07-07 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplier", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplierprofile",
            name="commercial_recored",
            field=models.ImageField(
                default="commercial_records/default.png", upload_to="commercial_records"
            ),
        ),
    ]
