# Generated by Django 5.0.6 on 2024-07-10 09:36

import supplier.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplier", "0002_alter_supplierprofile_commercial_recored"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="supplierprofile",
            name="brand_location",
        ),
        migrations.RemoveField(
            model_name="supplierprofile",
            name="brand_name",
        ),
        migrations.AddField(
            model_name="supplierprofile",
            name="city",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="supplierprofile",
            name="details",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="supplierprofile",
            name="district",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="supplierprofile",
            name="latitude",
            field=models.FloatField(
                default=0.0, validators=[supplier.utils.validate_lat]
            ),
        ),
        migrations.AddField(
            model_name="supplierprofile",
            name="longitude",
            field=models.FloatField(
                default=0.0, validators=[supplier.utils.validate_long]
            ),
        ),
        migrations.AddField(
            model_name="supplierprofile",
            name="phone_number",
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
