# Generated by Django 4.2 on 2024-03-31 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_feedback", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(name="complaints", table="complaints",),
        migrations.AlterModelTable(name="review", table="review",),
    ]
