# Generated by Django 4.2 on 2024-04-02 21:00

from django.db import migrations, models
import user_feedback.models


class Migration(migrations.Migration):

    dependencies = [
        ("user_feedback", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.IntegerField(
                default=0, validators=[user_feedback.models.validate_rating]
            ),
        ),
    ]
