# Generated by Django 5.0.6 on 2024-07-17 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
        ("promotion", "0002_coupon_products_to_earn"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="used_coupon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="promotion.usedcoupons",
            ),
        ),
    ]
