# Generated by Django 5.0.6 on 2024-07-19 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_alter_categoriesbrand_brand"),
        ("order", "0003_alter_order_shopping_cart"),
        ("wishlist_cart", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="shopping_cart",
        ),
        migrations.AddField(
            model_name="order",
            name="cart",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart",
                to="wishlist_cart.shoppingcart",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="OrderProducts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=1)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order",
                        to="order.order",
                    ),
                ),
                (
                    "products",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_detail",
                        to="catalog.productdetail",
                    ),
                ),
            ],
            options={
                "db_table": "order_products",
            },
        ),
        migrations.AddField(
            model_name="order",
            name="products",
            field=models.ManyToManyField(
                blank=True, through="order.OrderProducts", to="catalog.productdetail"
            ),
        ),
    ]
