# Generated by Django 5.0.6 on 2024-07-19 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0004_remove_order_shopping_cart_order_cart_orderproducts_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="total_cost",
        ),
        migrations.AddField(
            model_name="order",
            name="total_price",
            field=models.IntegerField(default=28464564),
            preserve_default=False,
        ),
    ]
