# Generated by Django 5.0.6 on 2024-07-19 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_alter_categoriesbrand_brand"),
        ("order", "0005_remove_order_total_cost_order_total_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderproducts",
            name="products",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart_product_detail",
                to="catalog.productdetail",
            ),
        ),
    ]
