# Generated by Django 5.0.6 on 2024-07-21 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0004_customerprofile_image_url"),
        ("order", "0006_alter_orderproducts_products"),
        ("supplier", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductBoughtFromSupplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("products_bought", models.IntegerField(default=0)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Users.customerprofile",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="supplier.supplierprofile",
                    ),
                ),
            ],
            options={
                "db_table": "productboughtfromsupplier",
            },
        ),
    ]
