# Generated by Django 5.0.6 on 2024-07-21 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "order",
            "0008_rename_products_bought_productboughtfromsupplier_quantity_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="productboughtfromsupplier",
            old_name="quantity",
            new_name="products_bought",
        ),
        migrations.RemoveField(
            model_name="productboughtfromsupplier",
            name="product",
        ),
    ]
