# Generated by Django 5.0.6 on 2024-07-21 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0004_customerprofile_image_url"),
        (
            "order",
            "0009_rename_quantity_productboughtfromsupplier_products_bought_and_more",
        ),
        ("supplier", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productboughtfromsupplier",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cus",
                to="Users.customerprofile",
            ),
        ),
        migrations.AlterField(
            model_name="productboughtfromsupplier",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sup",
                to="supplier.supplierprofile",
            ),
        ),
    ]
