# Generated by Django 5.0.6 on 2024-07-22 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0011_alter_order_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="pick_up_method",
            field=models.CharField(
                choices=[("BIKE", "Bike"), ("CAR", "Car"), ("TRUCK", "Truck")],
                default="CAR",
                max_length=9,
            ),
            preserve_default=False,
        ),
    ]
