# Generated by Django 5.0.6 on 2024-07-24 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("driver", "0004_vehicletypecategory"),
        ("order", "0012_order_pick_up_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="driver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="driver.driverprofile",
            ),
        ),
    ]
